### ISSUE TITLE
Keyerror 'result'

### ISSUE THREAD

**Issue by DasAuryn** [Eloise1988/OPENAI#2]
Exception has occurred: KeyError
'result'
  File "\robot.py", line 86, in Chatbot
    for result in data['result']:
  File "\robot.py", line 130, in main
    Chatbot()
  File "\robot.py", line 136, in <module>
    main()
KeyError: 'result'

**Comment by Eloise1988** [comment]
Looks like you are not loading the json from :
https://api.telegram.org/bot{BOT_TOKEN}/getUpdates

Check if you see your bots messages
