### ISSUE TITLE
Bot responds to replies, wasting tokens

### ISSUE THREAD

**Issue by dev-newb** [Eloise1988/OPENAI#3]
Since this implementation lacks a memory the bot doesn't understand that the user is replying to something the bot previously wrote (or a generated /img picture) so the bot simply completes / extends the user's sentence if it is a statement, if it is a question the bot answers without context from its past replies.

Can we add option to disable the bot replying to replies?

**Comment by Eloise1988** [comment]
You can now implement memory [here](https://github.com/Eloise1988/OPENAI/tree/main/asyncV2)
