### ISSUE TITLE
Request error in Chatbot function

### ISSUE THREAD

**Issue by SG1103** [Eloise1988/OPENAI#5]
when running the code I get this error "requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))" which is originates when this line is run "response = requests.get(url)"

**Comment by Eloise1988** [comment]
Is the connection error originating from the OpenAI endpoint or Telegram? There have been reports of connection issues with OpenAI, possibly due to high demand.
