### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by BuXaLo** [Eloise1988/OPENAI#6]
File "robot.py", line 21
    headers={'Authorization': f'Bearer {API_KEY}'},
                                                ^
SyntaxError: invalid syntax

**Comment by Eloise1988** [comment]
Make sure you have entered your Access Token in the following : Line 8
# OpenAI secret Key
API_KEY = 'xxxxxxxxxxxsecretAPIxxxxxxxxxx'
